apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: simplest
spec:
  resources:
    limits:
      memory: 8Gi
      cpu: 1000m
    requests:
      memory: 8Gi
      cpu: 1000m
  storage:
    traces:
      backend: s3
      s3:
        secret: minio
  jaegerui:
    enabled: true
    route:
      enabled: true
  observability:
    metrics:
      serviceMonitors:
        enabled: true
