apiVersion: batch/v1
kind: Job
metadata:
  name: generate-traces
  namespace: tempo-perf-test
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: loadgen
          image: ghcr.io/honeycombio/loadgen/loadgen:latest
          args:
            - --dataset=loadtest
            - --tps=150
            - --depth=10
            - --nspans=50
            - --runtime=30m
            - --ramptime=1s
            - --tracecount=0
            - --protocol=grpc
            - --sender=otel
            - --host=tempo-simplest:4317
            - --insecure
      restartPolicy: Never
  backoffLimit: 4

