{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Query Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(query_load_test_tempo_perf_test_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(query_load_test_tempo_perf_test_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Total Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tempo_receiver_accepted_spans", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accepted Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(tempo_receiver_accepted_spans[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(tempo_receiver_refused_spans[1m])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (rate(container_cpu_usage_seconds_total{pod=\"tempo-simplest-0\", container!=\"\"}[5m]))\n  /\n  sum by (pod) (kube_pod_container_resource_limits{pod=\"tempo-simplest-0\", resource=\"cpu\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(pod) (container_memory_usage_bytes{pod=\"tempo-simplest-0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}