apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: test-perfscale
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  observability:
    metrics:
      createPrometheusRules: true
      createServiceMonitors: true
  template:
      jaegerQuery:
        enabled: true
  storage:
    secret:
      type: s3
      name: s3-secret
  storageSize: 10Gi

