apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: simplest
  namespace: tempo-perf-test
spec:
  storage:
    traces:
      backend: s3
      s3:
        secret: minio
  jaegerui:
    enabled: true
    route:
      enabled: true
